function [ microphones , speaker ] = setupMAudioDev( inChanMap,outChanMap, SampleRate, frameSize )
%SETUPMAUDIODEV Summary of this function goes here
%   Detailed explanation goes here

    microphones = dsp.AudioRecorder(...
                'DeviceName', 'ProFire 610', ...
                'SampleRate', SampleRate, ...
                'OutputDataType','double',...
                'QueueDuration', 1,...
                'SamplesPerFrame', frameSize ,...
                'ChannelMappingSource','Property',...
                'ChannelMapping', inChanMap);
    speaker=dsp.AudioPlayer('DeviceName','ProFire 610','SampleRate', SampleRate,...
                    'ChannelMappingSource','Property',...
                    'ChannelMapping', outChanMap,'QueueDuration', 1);
end

